name: build-and-push

on: # condition to start the action "jobs"
  push:
    branches:
      - "main" 

jobs: # gets activeted if the condition is met
  build:
    runs-on: ubuntu-latest # version of os that the machine of github will run on
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # This step checkouts the code of the repository
      - name: Login to Docker Hub
        uses: docker/login-action@v2 # This step logs in to the Docker Hub using the secrets
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # info that is stored in github secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # This step sets up Buildx, a tool that allows building images
      - name: Build and push
        uses: docker/build-push-action@v3 # This step performs the actual build and push to Docker Hub
        with: 
          context: . # the file that the placed is placed in
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my_first_docker_repo:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          # Cache the image layers using a github action
          cache-from: type=gha
          cache-to: type=gha,mode=max
